2024-09-13 21:09:12,101 INFO    StreamThr :32232 [internal.py:wandb_internal():85] W&B internal server running at pid: 32232, started at: 2024-09-13 21:09:12.100138
2024-09-13 21:09:12,101 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: status
2024-09-13 21:09:12,104 INFO    WriterThread:32232 [datastore.py:open_for_write():87] open: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\run-tuhiqioi.wandb
2024-09-13 21:09:12,104 DEBUG   SenderThread:32232 [sender.py:send():379] send: header
2024-09-13 21:09:12,144 DEBUG   SenderThread:32232 [sender.py:send():379] send: run
2024-09-13 21:09:12,688 INFO    SenderThread:32232 [dir_watcher.py:__init__():211] watching files in: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files
2024-09-13 21:09:12,688 INFO    SenderThread:32232 [sender.py:_start_run_threads():1188] run started: tuhiqioi with start time 1726254552.102199
2024-09-13 21:09:12,693 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: check_version
2024-09-13 21:09:12,693 DEBUG   SenderThread:32232 [sender.py:send_request():406] send_request: check_version
2024-09-13 21:09:12,932 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: run_start
2024-09-13 21:09:12,975 DEBUG   HandlerThread:32232 [system_info.py:__init__():26] System info init
2024-09-13 21:09:12,975 DEBUG   HandlerThread:32232 [system_info.py:__init__():41] System info init done
2024-09-13 21:09:12,975 INFO    HandlerThread:32232 [system_monitor.py:start():194] Starting system monitor
2024-09-13 21:09:12,975 INFO    SystemMonitor:32232 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-13 21:09:12,975 INFO    HandlerThread:32232 [system_monitor.py:probe():214] Collecting system info
2024-09-13 21:09:12,982 INFO    SystemMonitor:32232 [interfaces.py:start():188] Started cpu monitoring
2024-09-13 21:09:12,982 INFO    SystemMonitor:32232 [interfaces.py:start():188] Started disk monitoring
2024-09-13 21:09:12,983 INFO    SystemMonitor:32232 [interfaces.py:start():188] Started gpu monitoring
2024-09-13 21:09:12,990 INFO    SystemMonitor:32232 [interfaces.py:start():188] Started memory monitoring
2024-09-13 21:09:12,999 INFO    SystemMonitor:32232 [interfaces.py:start():188] Started network monitoring
2024-09-13 21:09:13,007 DEBUG   HandlerThread:32232 [system_info.py:probe():152] Probing system
2024-09-13 21:09:13,007 DEBUG   HandlerThread:32232 [system_info.py:_probe_git():137] Probing git
2024-09-13 21:09:13,069 DEBUG   HandlerThread:32232 [system_info.py:_probe_git():145] Probing git done
2024-09-13 21:09:13,069 DEBUG   HandlerThread:32232 [system_info.py:probe():200] Probing system done
2024-09-13 21:09:13,069 DEBUG   HandlerThread:32232 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.18', 'heartbeatAt': '2024-09-13T19:09:13.007025', 'startedAt': '2024-09-13T19:09:12.088797', 'docker': None, 'cuda': None, 'args': ('--target_encoding', 'EGT', '--seed', '7', '--wandb_proj', 'DeepPurposePP', '--lr', '0.00001', '--epochs', '150'), 'state': 'running', 'program': 'E:\\DeepPurposePlusPlus\\train\\beta.py', 'codePathLocal': 'train\\beta.py', 'codePath': 'train\\beta.py', 'git': {'remote': 'https://github.com/jiaqingxie/DeepPurposePlusPlus.git', 'commit': 'fc4967e97e933fa57fa7827507251d728b2cc7f1'}, 'email': 'jiaxie@student.ethz.ch', 'root': 'E:/DeepPurposePlusPlus', 'host': 'DESKTOP-E5HJ25M', 'username': '嘉庆', 'executable': 'E:\\anaconda3\\envs\\graph\\python.exe', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 2100.0, 'min': 0.0, 'max': 2100.0}, 'cpu_freq_per_core': [{'current': 2100.0, 'min': 0.0, 'max': 2100.0}], 'disk': {'/': {'total': 214.84276962280273, 'used': 101.26670455932617}}, 'gpu': 'NVIDIA GeForce RTX 4070 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4070 Laptop GPU', 'memory_total': 8585740288}], 'memory': {'total': 15.812370300292969}}
2024-09-13 21:09:13,069 INFO    HandlerThread:32232 [system_monitor.py:probe():224] Finished collecting system info
2024-09-13 21:09:13,069 INFO    HandlerThread:32232 [system_monitor.py:probe():227] Publishing system info
2024-09-13 21:09:13,069 DEBUG   HandlerThread:32232 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-09-13 21:09:13,070 ERROR   HandlerThread:32232 [system_info.py:_save_conda():223] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 216, in _save_conda
    subprocess.call(
  File "E:\anaconda3\envs\graph\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "E:\anaconda3\envs\graph\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\anaconda3\envs\graph\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2024-09-13 21:09:13,072 DEBUG   HandlerThread:32232 [system_info.py:_save_conda():224] Saving conda packages done
2024-09-13 21:09:13,072 INFO    HandlerThread:32232 [system_monitor.py:probe():229] Finished publishing system info
2024-09-13 21:09:13,082 DEBUG   SenderThread:32232 [sender.py:send():379] send: files
2024-09-13 21:09:13,082 INFO    SenderThread:32232 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-09-13 21:09:13,270 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: python_packages
2024-09-13 21:09:13,271 DEBUG   SenderThread:32232 [sender.py:send_request():406] send_request: python_packages
2024-09-13 21:09:13,271 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: stop_status
2024-09-13 21:09:13,271 DEBUG   SenderThread:32232 [sender.py:send_request():406] send_request: stop_status
2024-09-13 21:09:13,272 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:13,610 DEBUG   SenderThread:32232 [sender.py:send():379] send: telemetry
2024-09-13 21:09:13,610 DEBUG   SenderThread:32232 [sender.py:send():379] send: config
2024-09-13 21:09:13,694 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:13,694 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\wandb-metadata.json
2024-09-13 21:09:13,694 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\conda-environment.yaml
2024-09-13 21:09:13,694 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\requirements.txt
2024-09-13 21:09:13,839 INFO    wandb-upload_0:32232 [upload_job.py:push():130] Uploaded file C:\Users\嘉庆\AppData\Local\Temp\tmprdbnyg2_wandb\0sw39hmc-wandb-metadata.json
2024-09-13 21:09:14,262 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:15,313 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:15,703 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:16,358 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:17,208 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: status_report
2024-09-13 21:09:17,445 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:17,708 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:17,842 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:18,424 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:19,457 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:19,721 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:19,843 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:20,492 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:21,559 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:21,742 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:21,874 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:22,287 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: status_report
2024-09-13 21:09:22,609 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:23,653 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:23,755 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:23,868 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:24,700 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:25,741 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:25,771 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:25,876 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:26,758 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:27,331 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: status_report
2024-09-13 21:09:27,776 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:27,832 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:27,888 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:28,310 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: stop_status
2024-09-13 21:09:28,310 DEBUG   SenderThread:32232 [sender.py:send_request():406] send_request: stop_status
2024-09-13 21:09:28,825 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:29,808 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:29,842 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:29,891 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:30,863 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:31,824 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:31,908 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:31,925 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:32,354 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: status_report
2024-09-13 21:09:32,940 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:33,830 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:33,964 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:34,010 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:35,007 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:35,841 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:35,923 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:36,051 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:37,050 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:37,491 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: status_report
2024-09-13 21:09:37,850 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:37,933 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:38,057 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:39,093 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:39,866 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:39,970 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:40,119 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:41,143 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:41,874 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:41,959 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:42,176 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:42,540 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: status_report
2024-09-13 21:09:42,711 ERROR   SenderThread:32232 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-13 21:09:42,711 ERROR   SenderThread:32232 [internal_api.py:execute():350] {"errors":[{"message":"run tuhiqioi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-13 21:09:43,208 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:43,383 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: stop_status
2024-09-13 21:09:43,891 INFO    Thread-16 :32232 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\files\output.log
2024-09-13 21:09:44,125 ERROR   SenderThread:32232 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-13 21:09:44,125 ERROR   SenderThread:32232 [internal_api.py:execute():350] {"errors":[{"message":"run tuhiqioi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-13 21:09:44,140 ERROR   FileStreamThread:32232 [file_stream.py:_handle_response():510] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/jiaqing/DeepPurposePP/tuhiqioi/file_stream
NoneType: None
2024-09-13 21:09:44,224 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:45,259 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:46,274 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:46,752 ERROR   SenderThread:32232 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-13 21:09:46,752 ERROR   SenderThread:32232 [internal_api.py:execute():350] {"errors":[{"message":"run tuhiqioi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-13 21:09:46,752 INFO    SenderThread:32232 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "E:\anaconda3\envs\graph\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-09-13 21:09:47,309 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:48,337 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:49,365 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:50,390 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:51,457 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:51,940 ERROR   SenderThread:32232 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-13 21:09:51,940 ERROR   SenderThread:32232 [internal_api.py:execute():350] {"errors":[{"message":"run tuhiqioi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-13 21:09:52,440 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:53,474 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:54,490 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:55,540 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:56,607 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:57,640 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:58,658 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:09:59,725 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:00,709 ERROR   SenderThread:32232 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-13 21:10:00,709 ERROR   SenderThread:32232 [internal_api.py:execute():350] {"errors":[{"message":"run tuhiqioi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-13 21:10:00,792 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:01,829 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:02,890 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:03,949 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:05,007 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:06,041 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:07,057 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:08,082 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:09,142 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:10,157 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:11,197 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:12,257 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:13,000 DEBUG   SystemMonitor:32232 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-13 21:10:13,311 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:14,400 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:15,463 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:16,473 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:17,507 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:18,535 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:19,597 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:20,540 ERROR   SenderThread:32232 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-13 21:10:20,540 ERROR   SenderThread:32232 [internal_api.py:execute():350] {"errors":[{"message":"run tuhiqioi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-13 21:10:20,634 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:21,673 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:22,729 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:23,757 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:24,845 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:25,836 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:26,876 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:27,939 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:28,981 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:30,019 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:31,057 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:32,056 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:33,085 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:34,103 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:35,130 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:36,165 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:37,191 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:38,253 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:39,256 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:40,310 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:41,290 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:42,319 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:43,349 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:44,379 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:45,420 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:46,460 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:47,453 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:48,479 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:49,502 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:50,528 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:51,566 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:52,575 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:53,613 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:54,639 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:55,650 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:56,674 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:57,697 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:58,719 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:10:59,729 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:00,090 ERROR   SenderThread:32232 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-13 21:11:00,090 ERROR   SenderThread:32232 [internal_api.py:execute():350] {"errors":[{"message":"run tuhiqioi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-13 21:11:00,768 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:01,792 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:02,799 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:03,825 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:04,847 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:05,854 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:06,877 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:07,885 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:08,908 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:09,948 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:10,956 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:11,980 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:13,003 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:14,044 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:15,099 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:16,123 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:17,163 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:18,203 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:19,226 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:20,258 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:21,323 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:22,348 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:23,375 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:24,368 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:25,426 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:26,402 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:27,404 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:28,409 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:29,418 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:30,421 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:31,429 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:32,432 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:33,435 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:34,438 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:35,453 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:36,458 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:37,464 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:38,471 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:39,474 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:40,480 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:41,487 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:42,493 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:43,497 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:44,502 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:45,507 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:46,512 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:47,517 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:48,524 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:49,535 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:50,544 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:51,556 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:52,565 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:53,570 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:54,575 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:55,580 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:56,585 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:57,590 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:58,595 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:11:59,600 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:12:00,606 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:12:01,612 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:12:02,621 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-13 21:12:04,490 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-13 21:12:09,536 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: keepalive
2024-09-13 21:12:14,596 DEBUG   HandlerThread:32232 [handler.py:handle_request():158] handle_request: keepalive
2024-09-13 21:12:17,136 ERROR   SenderThread:32232 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-13 21:12:17,136 ERROR   SenderThread:32232 [internal_api.py:execute():350] {"errors":[{"message":"run tuhiqioi was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-13 21:12:17,615 INFO    HandlerThread:32232 [handler.py:finish():882] shutting down handler
2024-09-13 21:12:17,615 INFO    HandlerThread:32232 [system_monitor.py:finish():203] Stopping system monitor
2024-09-13 21:12:17,616 INFO    HandlerThread:32232 [interfaces.py:finish():200] Joined cpu monitor
2024-09-13 21:12:17,616 DEBUG   SystemMonitor:32232 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-13 21:12:17,616 DEBUG   SystemMonitor:32232 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-13 21:12:17,616 INFO    HandlerThread:32232 [interfaces.py:finish():200] Joined disk monitor
2024-09-13 21:12:17,663 INFO    HandlerThread:32232 [interfaces.py:finish():200] Joined gpu monitor
2024-09-13 21:12:17,663 INFO    HandlerThread:32232 [interfaces.py:finish():200] Joined memory monitor
2024-09-13 21:12:17,663 INFO    HandlerThread:32232 [interfaces.py:finish():200] Joined network monitor
2024-09-13 21:12:18,079 INFO    WriterThread:32232 [datastore.py:close():296] close: E:\DeepPurposePlusPlus\wandb\run-20240913_210912-tuhiqioi\run-tuhiqioi.wandb
2024-09-13 21:12:18,080 ERROR   StreamThr :32232 [internal.py:wandb_internal():173] Thread SenderThread:
Traceback (most recent call last):
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2224, in upsert_run
    response = self.gql(
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\internal_api.py", line 317, in gql
    ret = self._retry_gql(
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "E:\anaconda3\envs\graph\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\internal_util.py", line 48, in run
    self._run()
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\internal_util.py", line 92, in _run
    self._debounce()
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\internal.py", line 333, in _debounce
    self._sm.debounce()
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\sender.py", line 537, in debounce
    self._maybe_update_config(always=final)
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\sender.py", line 514, in _maybe_update_config
    self._debounce_config()
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\sender.py", line 543, in _debounce_config
    self._api.upsert_run(
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\apis\normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run tuhiqioi was previously created and deleted; try a new run name (Error 409: Conflict)
