Protein Function Prediction Mode...
in total: 8420 proteins
encoding protein...
unique target sequence: 8383
Done.
Protein Function Prediction Mode...
in total: 2811 proteins
encoding protein...
unique target sequence: 2807
Done.
Protein Function Prediction Mode...
in total: 2773 proteins
encoding protein...
unique target sequence: 2768
Done.
Let's use 1 GPU!
--- Data Preparation ---
--- Go for Training ---
Training at Epoch 1 iteration 0 with loss 2.30419. Total time 0.00833 hours
E:\anaconda3\envs\graph\lib\site-packages\torch\autograd\graph.py:744: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Training at Epoch 1 iteration 100 with loss 2.13480. Total time 0.00972 hours
Training at Epoch 1 iteration 200 with loss 1.72849. Total time 0.01083 hours
Validation at Epoch 1 , Accuracy: 0.28779 , AUPRC: 0.16521 , F1: 0.04469
--- Go for Testing ---
[5 5 9 ... 5 0 4]
Traceback (most recent call last):
  File "E:\DeepPurposePlusPlus\train\subcellular.py", line 88, in <module>
    model.train(train, val, test, compute_pos_enc = compute_pos)
  File "E:\DeepPurposePlusPlus\ProB\ProteinPred.py", line 482, in train
    acc, auprc, f1, logits = self.test_(testing_generator, model_max, test=True, verbose=verbose)
  File "E:\DeepPurposePlusPlus\ProB\ProteinPred.py", line 230, in test_
    plot_confusion_matrix(multi_y_pred, y_label, roc_auc_file, self.target_encoding)
  File "E:\DeepPurposePlusPlus\ProB\utils.py", line 110, in plot_confusion_matrix
    cm = confusion_matrix(y_label, y_pred)
  File "E:\anaconda3\envs\graph\lib\site-packages\sklearn\utils\_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "E:\anaconda3\envs\graph\lib\site-packages\sklearn\metrics\_classification.py", line 326, in confusion_matrix
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "E:\anaconda3\envs\graph\lib\site-packages\sklearn\metrics\_classification.py", line 93, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets